otel.service.name=leoni-backend
otel.exporter.otlp.endpoint=https://ingest.us2.signoz.cloud:443
otel.exporter.otlp.headers=signoz-access-token=AMxUjrMlgzhRKwk8/19Gvx6tnEUiOtiuIJoOoGNdeH4=
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp
