otel.service.name=leoni-backend
otel.exporter.otlp.endpoint=https://ingest.us2.signoz.cloud:443
otel.exporter.otlp.headers=signoz-access-token=YttROPAHE7WkIZsoV98t-nPMdiwOqPVpyL2Y
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp