otel.service.name=leoni-backend
otel.exporter.otlp.endpoint=https://ingest.us2.signoz.cloud:443
otel.exporter.otlp.headers=signoz-access-token=1epqodm2TMc4eY4KjuPdCUHqQwsWKpL%2B0s/Bc4hYJCo=
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp
