# ===============================
# = ACTIVE PROFILE
# ===============================
spring.profiles.active=dev

# ===============================
# = COMMON CONFIGURATION
# ===============================
app.base-url=http://localhost:4200
server.port=8081

# ===============================
# = JWT SECURITY
# ===============================
application.security.jwt.secret-key=37cc86b9634742f0e5218b71ee3e7b50897e388eb2d28229fca054e3ac6619d0
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000