# ===============================
# = ACTIVE PROFILE
# ===============================
spring.profiles.active=docker

# ===============================
# = COMMON CONFIGURATION
# ===============================
app.base-url=http://localhost:4200
server.port=8080

# ===============================
# = JWT SECURITY
# ===============================
application.security.jwt.secret-key=37cc86b9634742f0e5218b71ee3e7b50897e388eb2d28229fca054e3ac6619d0
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
# Dans src/main/resources/application-docker.properties
spring.datasource.hikari.maximumPoolSize=2
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.connectionTimeout=20000