# ===============================
# = DATA SOURCE (MySQL)
# ===============================
app.base-url=http://localhost:4200

spring.datasource.url=jdbc:mysql://localhost:3306/testmodulesleonipfe?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Dossier uploads à la racine du projet
spring.web.resources.static-locations=file:uploads/

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# ===============================
# = JWT SECURITY
# ===============================

application.security.jwt.secret-key=37cc86b9634742f0e5218b71ee3e7b50897e388eb2d28229fca054e3ac6619d0
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000


# ===============================
# = SERVER
# ===============================

server.port=8086
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leonisystem.notifications@gmail.com
spring.mail.password=ydzkefjojpladzht
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Logs détaillés pour le mail
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
# DÉSACTIVER LA VALIDATION SSL
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.starttls.required=false

# Désactiver la vérification d'hôte
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false